---
title: "02-APR-2026 UPDATE"
date: 2026-04-02
format: html
categories: [Updates]
---

Hi, all:

**What I did last week.** I wrapped up my custom HEDIS ontology; I still need to add the blog post.

**What I'm doing this week.** Just spent 3-4 hours trying to write SPARQL queries in the Protege desktop app. It was a disaster. It was also like my third time trying to figure it all out… I’ll expand on the technical details below…

**Technical Challenges.** Protege desktop app is a mess. Apparently there’s a known issue that causes the SPARQL query editor window to disappear when you load an ontology—not at all helpful, but what can you expect from free software. Most users have switched to a plug-in called Snap SPARQL, but its syntax is so, so awful and there’s no documentation for it online; I cannot get it to return anything from my BioPortal ontology. Oh, and BioPortal deprecated its built-in SPARQL engine years ago. I guess that’s what you get when you’re trying to get experience in a really, really niche domain like this one. I’m getting to skip ahead to seeing what I can do with SPARQL in Python.

An aside: I started a new role and there was some discussion about needing a cohesive, domain-specific semantic data layer to be able to really roll out AI enterprise wide. That discussion got me interested in this project (again). I can see huge (lucrative) business potential in being able to deliver individual, proprietary, semantic data packages to these companies…

But how the heck do you even begin with something like that?