---
title: "ONTOLOGY DEVELOPMENT - PART 1"
date: 2026-03-19
format: html
categories: [OWL, Protege]
---

## INTRODUCTION

Before I begin querying an existing ontology like those on BioPortal, I’ll attempt to develop my own ontology. I’ll loosely follow the Protégé guide to ontology development, *Ontology Development 101: A Guide to Creating Your First Ontology*, by Noy and McGuinness (2001):[Ontology Development 101: A Guide to Creating Your First Ontology](https://protege.stanford.edu/publications/ontology_development/ontology101.pdf)

There are a handful of reasons why we create ontologies, but most importantly, we create ontologies to share our understanding of _domain-specific knowledge_. I’ll develop an ontology specific to my domain of career expertise: _health quality measurement_. More specifically, I’ll develop an ontology that describes components of the Healthcare Effectiveness Data and Information Set (HEDIS) published by the National Committee for Quality Assurance (NCQA). If you want to see the full set of HEDIS measures and how they’re defined, you’ll need to purchase a copy of _HEDIS Volume 2_ and its technical specifications. Instead, you can review a summary of HEDIS measures used by Johns Hopkins Health Plans as part of their Health Care Performance Measures: [HEDIS Quality Measure Toolkit](https://www.hopkinsmedicine.org/johns-hopkins-health-plans/providers-physicians/health-care-performance-measures/hedis)

---

## STEP 1: DETERMINE THE DOMAIN & SCOPE OF THE ONTOLOGY

Noy and McGuinness suggest that the following questions should be answered prior to publishing an ontology:

- What is the domain that the ontology will cover?  
- How will the ontology be used?  
- What questions will the ontology be able to answer?  
- Who will use and maintain the ontology?  

Here are my answers:

- My ontology will be used in the domain of healthcare quality measurement; I’ll begin with HEDIS measures, specifically, but it could be amended to include more measurement schemes in the future. 
- My ontology will be used to support the development of interoperable technologies that report healthcare quality measures (like HEDIS) from disparate sources of electronic health information.
- My ontology will also help to answer questions about the overlap between similar healthcare quality measures. 
- I don't plan to publish my ontology, but I would (presumably) be responsible for maintaining it.


## COMPETENCY QUESTIONS

A list of **competency questions** can also be helpful for understanding the proposed information content of the ontology. If the ontology can’t be used to answer the questions, then more information needs to be added. For now, I’ll begin with the following, simple question: 

*How much informational overlap is there between any two HEDIS measures?*

---

## STEP 2: CONSIDER RE-USING EXISTING ONTOLOGIES

There aren't any.

Next...

---

## STEP 3: ENUMERATE IMPORTANT TERMS IN THE ONTOLOGY

Now, I will list the key terms that should be included in the ontology. For example, an ontology for wines would include terms like `grape`, `location`, and `winery`.

For my ontology, initial terms include:

- `product line` (e.g., Medicaid)  
- `value sets`  
- `codes`  
- `code systems`  
- `medications`  

My list will probably grow as I continue...

---

## NEXT STEPS

In **Part 2**, I will begin defining classes and class hierarchies.