---
title: "WHAT OWLS KNOW"
date: 2026-03-02
categories: [OWL]
---

We’re told that owls are the most wise of all birds. As children, we’re told to revere the wisdom of these bespectacled, nocturnal, hunters but without any evidence that they’re smarter than, say, a… woodcock, a bird that I think appears equally perceptive. But let’s suspend disbelief and assume that owls are the wisest of the bird kingdom. Then, let’s suspend disbelief again and imagine that owls can find employment as computer scientists or informaticists. 

Being wise as they are, owls would certainly endorse a codified, international, standard for describing domain-specific knowledge. Maybe it’s no coincidence that OWL has become W3C’s standard language for authoring an ontology: a structured description of concepts, and the relationship between them, within some domain of knowledge.

OWL became W3C’s semantic language of choice in 2004, over 20 years ago, not long after Tim Berners-Lee proposed the so-called Semantic Web as the rebirth of the World Wide Web. Berners-Lee imagined ripping out the web’s tangled mess of hyperlinks and replacing them all with a systematic, interconnected, web of datapoints described, and separated by, the relationships between themselves. Unlike the World Wide Web, the Semantic Web would be machine-readable and allow for more automated processing.

It never happened. Nobody wanted to remake their website with semantic web standards. Then LLMs were unleashed on the world. After being trained on millions and millions of documents scraped from the web, they “learned” how to read information from the unstructured, supposedly unreadable, World Wide Web.

So why do we still care about semantic data architecture? Learning OWL sounds about as useful as learning a dead language like Latin.

LLMs, despite hastening the early death of the Semantic Web, benefit from a little structured data on top of the massive ocean of unstructured data that feeds their abilities. This so-called semantic layer refines their output, adds precision to their responses, and prevents hallucinations. Semantic descriptions of data provide domain-specific context that allow AI tools to generate consistent, business-friendly outputs.

LLMs might even help us with some of the drudgery that prevented the realization of Tim Berger-Lee’s semantic web.

Not even an owl could’ve seen that coming.